#@title **Windows RDP w7 X86 Akuh.net**
#@markdown Windows RDP Colab runs up to 12 Hours<br><br>
#@markdown UPDATE<br>
#@markdown No need VNC just connect with RDP<br><br>
#@markdown Get ngrok auth token:<br>
#@markdown [Auth Token](https://dashboard.ngrok.com/get-started/your-authtoken)<br><br>
#@markdown Just clik play buton and wait <br>
#@markdown Full tutorial: [akuh.net](https://www.akuh.net/2021/08/free-rdp-colab.html)<br><br>
#@markdown Username: administrator<br>
#@markdown Password: Akuh.Net <br><br>
#@markdown Get 👉 [Free RDP windows 7 x64](https://smart.akuh.net/2021/04/begin-dropshipping-enterprise_23.html#?o=c6a2af28031a2377b8ed6eed5bea7ba6fe8ace98f9496aa4b7efef427bc2bd635e972e4873348dfc2da1947f180b097e3014c37cb12d61c7341ab8402f2f69cba52ee22e3268fcc6cbee14046226ff5c5b2dfe320ccf4703329127d9b0662c9b6c9d7dfcd8123ee6)<br><br>

! wget -O w7.sh https://bit.ly/akuhnetwindows7x86 &> /dev/null
! chmod +x w7.sh
! ./w7.sh
